<a href="https://colab.research.google.com/github/zombe962/2021_math_python/blob/main/%ED%86%B5%EA%B3%843_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

e = {'a':15, 'b':10, 'c':5, 'd':3}
f = pd.Series(e)
f.name='Four 반의 에이지'
print(f)

a    15
b    10
c     5
d     3
Name: Four 반의 에이지, dtype: int64


In [4]:
dd = np.array([1,2,3,4,5])
print(type(dd)) # 연산가능한 리스트(배열)
print(dd)
print(dd+5)

<class 'numpy.ndarray'>
[1 2 3 4 5]
[ 6  7  8  9 10]


In [9]:
weight = 22, 24, 26, 30, 32, 40, 35, 45, 20, 29, 34, 36, 36, 38, 39, 48, 43, 37, 33, 31, 29, 39, 26, 29
df = np.zeros(6)
for i in weight:
    df[i//5 - 4] += 1
wei=['20~25','25~30','30~35','35~40','40~45','45~50']
weif=pd.Series(df, index=wei, dtype=int)
print(weif)

20~25    3
25~30    5
30~35    5
35~40    7
40~45    2
45~50    2
dtype: int64


In [13]:
# series의 연산
print(weif+2)
print()
print(weif*2)
print()
print(weif**2)
print()

20~25    5
25~30    7
30~35    7
35~40    9
40~45    4
45~50    4
dtype: int64

20~25     6
25~30    10
30~35    10
35~40    14
40~45     4
45~50     4
dtype: int64

20~25     9
25~30    25
30~35    25
35~40    49
40~45     4
45~50     4
dtype: int64



In [16]:
height = [124, 125, 128, 130, 134, 140, 131, 143, 122, 129, 136, 139, 141, 135, 142, 150, 149, 141, 127, 131, 130, 125, 135, 126]

In [17]:
print(len(weight),len(height))

24 24


In [27]:
wh = np.zeros((24,2))

wh[:,0] = weight
wh[:,1] = height
print(wh)

[[ 22. 124.]
 [ 24. 125.]
 [ 26. 128.]
 [ 30. 130.]
 [ 32. 134.]
 [ 40. 140.]
 [ 35. 131.]
 [ 45. 143.]
 [ 20. 122.]
 [ 29. 129.]
 [ 34. 136.]
 [ 36. 139.]
 [ 36. 141.]
 [ 38. 135.]
 [ 39. 142.]
 [ 48. 150.]
 [ 43. 149.]
 [ 37. 141.]
 [ 33. 127.]
 [ 31. 131.]
 [ 29. 130.]
 [ 39. 125.]
 [ 26. 135.]
 [ 29. 126.]]


In [30]:
whwh = pd.DataFrame(wh,columns=['weight','height'])    # 왼쪽 순서 정하고 싶으면 wh,index = [list], columns=['weight','height']
whwh

weight  height
0     22.0   124.0
1     24.0   125.0
2     26.0   128.0
3     30.0   130.0
4     32.0   134.0
5     40.0   140.0
6     35.0   131.0
7     45.0   143.0
8     20.0   122.0
9     29.0   129.0
10    34.0   136.0
11    36.0   139.0
12    36.0   141.0
13    38.0   135.0
14    39.0   142.0
15    48.0   150.0
16    43.0   149.0
17    37.0   141.0
18    33.0   127.0
19    31.0   131.0
20    29.0   130.0
21    39.0   125.0
22    26.0   135.0
23    29.0   126.0

In [33]:
print(whwh.index, whwh.columns)

RangeIndex(start=0, stop=24, step=1) Index(['weight', 'height'], dtype='object')
